# -*- coding: utf-8 -*-
"""FoodClassifierapp.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ag8trqrF-MKZuZGI1ebkfKY1uMCj1EAi
"""

import streamlit as st
from PIL import Image
import numpy as np
import pickle
import gdown
import requests

import streamlit as st
import requests
import pickle

# Downloading the pickled model from Google Drive using url
def download_pickled_model(url):
    response = requests.get('1--DVdrhXvkkNVh_vDhm7SYWVy3LEOmcQ/')
    with open('mongolian.food.pkl', 'wb') as f:
        f.write(response.content)

# Load the pickled model
def load_model():
    with open('mongolian.food.pkl', 'rb') as f:
        foodclassifier = pickle.load(f)
    return foodclassifier

def predict_image(image, foodclassifier):
    prediction = foodclassifer.predict(image)
    return prediction

def main():
    st.title("Mongolian Food Classifier")

    # File uploader widget
    uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        # Read image
        image = Image.open(uploaded_file)
        st.image(image, caption="Uploaded Image", use_column_width=True)

        # Convert image to numpy array and preprocess
        image_array = np.array(image)

        # Make prediction
        prediction = predict_image(image_array, foodclassifier)

        # Display prediction
        st.subheader("Prediction:")
        st.write(prediction)

if __name__ == "__main__":
    main()